/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dashj.bls;

public class AugSchemeMPL extends CoreMPL {
  private transient long swigCPtr;

  protected AugSchemeMPL(long cPtr, boolean cMemoryOwn) {
    super(DASHJBLSJNI.AugSchemeMPL_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AugSchemeMPL obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DASHJBLSJNI.delete_AugSchemeMPL(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static String getCIPHERSUITE_ID() {
    return DASHJBLSJNI.AugSchemeMPL_CIPHERSUITE_ID_get();
  }

  public AugSchemeMPL() {
    this(DASHJBLSJNI.new_AugSchemeMPL(), true);
  }

  public G2Element sign(PrivateKey seckey, byte[] message) {
    return new G2Element(DASHJBLSJNI.AugSchemeMPL_sign__SWIG_0(swigCPtr, this, PrivateKey.getCPtr(seckey), seckey, message), true);
  }

  public G2Element sign(PrivateKey seckey, byte[] message, G1Element prepend_pk) {
    return new G2Element(DASHJBLSJNI.AugSchemeMPL_sign__SWIG_1(swigCPtr, this, PrivateKey.getCPtr(seckey), seckey, message, G1Element.getCPtr(prepend_pk), prepend_pk), true);
  }

  public boolean verify(byte[] pubkey, byte[] message, byte[] signature) {
    return DASHJBLSJNI.AugSchemeMPL_verify(swigCPtr, this, pubkey, message, signature);
  }

  public boolean aggregateVerify(Uint8VectorVector pubkeys, Uint8VectorVector messages, byte[] signature) {
    return DASHJBLSJNI.AugSchemeMPL_aggregateVerify__SWIG_0(swigCPtr, this, Uint8VectorVector.getCPtr(pubkeys), pubkeys, Uint8VectorVector.getCPtr(messages), messages, signature);
  }

  public boolean aggregateVerify(G1ElementVector pubkeys, Uint8VectorVector messages, G2Element signature) {
    return DASHJBLSJNI.AugSchemeMPL_aggregateVerify__SWIG_1(swigCPtr, this, G1ElementVector.getCPtr(pubkeys), pubkeys, Uint8VectorVector.getCPtr(messages), messages, G2Element.getCPtr(signature), signature);
  }

}
