/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dashj.bls;

public class BLS {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BLS(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BLS obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DASHJBLSJNI.delete_BLS(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static boolean init() {
    return DASHJBLSJNI.BLS_init();
  }

  public static void checkRelicErrors() {
    DASHJBLSJNI.BLS_checkRelicErrors();
  }

  public static int getContextError() {
    return DASHJBLSJNI.BLS_getContextError();
  }

  public static void setContextError(int error) {
    DASHJBLSJNI.BLS_setContextError(error);
  }

  public static int getContext() {
    return DASHJBLSJNI.BLS_getContext();
  }

  public BLS() {
    this(DASHJBLSJNI.new_BLS(), true);
  }

  public final static int MESSAGE_HASH_LEN = DASHJBLSJNI.BLS_MESSAGE_HASH_LEN_get();
  public final static int RLC_OK = DASHJBLSJNI.BLS_RLC_OK_get();
}
