/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dashj.bls;

public class ChainCode {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ChainCode(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChainCode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DASHJBLSJNI.delete_ChainCode(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static ChainCode fromBytes(byte[] bytes) {
    return new ChainCode(DASHJBLSJNI.ChainCode_fromBytes(bytes), true);
  }

  public ChainCode(ChainCode cc) {
    this(DASHJBLSJNI.new_ChainCode__SWIG_0(ChainCode.getCPtr(cc), cc), true);
  }

  public void serialize(byte[] buffer) {
    DASHJBLSJNI.ChainCode_serialize__SWIG_0(swigCPtr, this, buffer);
  }

  public byte[] serialize() { return DASHJBLSJNI.ChainCode_serialize__SWIG_1(swigCPtr, this); }

  public ChainCode() {
    this(DASHJBLSJNI.new_ChainCode__SWIG_1(), true);
  }

  public final static int SIZE = DASHJBLSJNI.ChainCode_SIZE_get();
}
