/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dashj.bls;

public class CoreMPL {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CoreMPL(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CoreMPL obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DASHJBLSJNI.delete_CoreMPL(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CoreMPL(String strId) {
    this(DASHJBLSJNI.new_CoreMPL(strId), true);
  }

  public PrivateKey keyGen(byte[] seed) {
    return new PrivateKey(DASHJBLSJNI.CoreMPL_keyGen(swigCPtr, this, seed), true);
  }

  public byte[] skToPk(PrivateKey seckey) { return DASHJBLSJNI.CoreMPL_skToPk(swigCPtr, this, PrivateKey.getCPtr(seckey), seckey); }

  public G1Element skToG1(PrivateKey seckey) {
    return new G1Element(DASHJBLSJNI.CoreMPL_skToG1(swigCPtr, this, PrivateKey.getCPtr(seckey), seckey), true);
  }

  public G2Element sign(PrivateKey seckey, byte[] message) {
    return new G2Element(DASHJBLSJNI.CoreMPL_sign(swigCPtr, this, PrivateKey.getCPtr(seckey), seckey, message), true);
  }

  public boolean verify(byte[] pubkey, byte[] message, byte[] signature) {
    return DASHJBLSJNI.CoreMPL_verify__SWIG_0(swigCPtr, this, pubkey, message, signature);
  }

  public boolean verify(G1Element pubkey, byte[] message, G2Element signature) {
    return DASHJBLSJNI.CoreMPL_verify__SWIG_1(swigCPtr, this, G1Element.getCPtr(pubkey), pubkey, message, G2Element.getCPtr(signature), signature);
  }

  public byte[] aggregate(Uint8VectorVector signatures) { return DASHJBLSJNI.CoreMPL_aggregate__SWIG_0(swigCPtr, this, Uint8VectorVector.getCPtr(signatures), signatures); }

  public G2Element aggregate(G2ElementVector signatures) {
    return new G2Element(DASHJBLSJNI.CoreMPL_aggregate__SWIG_1(swigCPtr, this, G2ElementVector.getCPtr(signatures), signatures), true);
  }

  public G1Element aggregate(G1ElementVector publicKeys) {
    return new G1Element(DASHJBLSJNI.CoreMPL_aggregate__SWIG_2(swigCPtr, this, G1ElementVector.getCPtr(publicKeys), publicKeys), true);
  }

  public G2Element aggregateSecure(G1ElementVector vecPublicKeys, G2ElementVector vecSignatures, byte[] message) {
    return new G2Element(DASHJBLSJNI.CoreMPL_aggregateSecure(swigCPtr, this, G1ElementVector.getCPtr(vecPublicKeys), vecPublicKeys, G2ElementVector.getCPtr(vecSignatures), vecSignatures, message), true);
  }

  public boolean verifySecure(G1ElementVector vecPublicKeys, G2Element signature, byte[] message) {
    return DASHJBLSJNI.CoreMPL_verifySecure(swigCPtr, this, G1ElementVector.getCPtr(vecPublicKeys), vecPublicKeys, G2Element.getCPtr(signature), signature, message);
  }

  public boolean aggregateVerify(Uint8VectorVector pubkeys, Uint8VectorVector messages, byte[] signature) {
    return DASHJBLSJNI.CoreMPL_aggregateVerify__SWIG_0(swigCPtr, this, Uint8VectorVector.getCPtr(pubkeys), pubkeys, Uint8VectorVector.getCPtr(messages), messages, signature);
  }

  public boolean aggregateVerify(G1ElementVector pubkeys, Uint8VectorVector messages, G2Element signature) {
    return DASHJBLSJNI.CoreMPL_aggregateVerify__SWIG_1(swigCPtr, this, G1ElementVector.getCPtr(pubkeys), pubkeys, Uint8VectorVector.getCPtr(messages), messages, G2Element.getCPtr(signature), signature);
  }

  public PrivateKey deriveChildSk(PrivateKey sk, long index) {
    return new PrivateKey(DASHJBLSJNI.CoreMPL_deriveChildSk(swigCPtr, this, PrivateKey.getCPtr(sk), sk, index), true);
  }

  public PrivateKey deriveChildSkUnhardened(PrivateKey sk, long index) {
    return new PrivateKey(DASHJBLSJNI.CoreMPL_deriveChildSkUnhardened(swigCPtr, this, PrivateKey.getCPtr(sk), sk, index), true);
  }

  public G1Element deriveChildPkUnhardened(G1Element sk, long index) {
    return new G1Element(DASHJBLSJNI.CoreMPL_deriveChildPkUnhardened(swigCPtr, this, G1Element.getCPtr(sk), sk, index), true);
  }

}
