/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dashj.bls;

public class GTElement {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GTElement(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GTElement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DASHJBLSJNI.delete_GTElement(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static GTElement fromBytes(byte[] bytes) {
    return new GTElement(DASHJBLSJNI.GTElement_fromBytes(bytes), true);
  }

  public static GTElement fromBytesUnchecked(byte[] bytes) {
    return new GTElement(DASHJBLSJNI.GTElement_fromBytesUnchecked(bytes), true);
  }

  public static GTElement unity() {
    return new GTElement(DASHJBLSJNI.GTElement_unity(), true);
  }

  public void serialize(byte[] buffer) {
    DASHJBLSJNI.GTElement_serialize__SWIG_0(swigCPtr, this, buffer);
  }

  public byte[] serialize() { return DASHJBLSJNI.GTElement_serialize__SWIG_1(swigCPtr, this); }

  public final static int SIZE = DASHJBLSJNI.GTElement_SIZE_get();
}
