/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dashj.bls;

public class PrivateKeyVector extends java.util.AbstractList<PrivateKey> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PrivateKeyVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PrivateKeyVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DASHJBLSJNI.delete_PrivateKeyVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PrivateKeyVector(PrivateKey[] initialElements) {
    this();
    reserve(initialElements.length);

    for (PrivateKey element : initialElements) {
      add(element);
    }
  }

  public PrivateKeyVector(Iterable<PrivateKey> initialElements) {
    this();
    for (PrivateKey element : initialElements) {
      add(element);
    }
  }

  public PrivateKey get(int index) {
    return doGet(index);
  }

  public PrivateKey set(int index, PrivateKey e) {
    return doSet(index, e);
  }

  public boolean add(PrivateKey e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, PrivateKey e) {
    modCount++;
    doAdd(index, e);
  }

  public PrivateKey remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public PrivateKeyVector() {
    this(DASHJBLSJNI.new_PrivateKeyVector__SWIG_0(), true);
  }

  public PrivateKeyVector(PrivateKeyVector other) {
    this(DASHJBLSJNI.new_PrivateKeyVector__SWIG_1(PrivateKeyVector.getCPtr(other), other), true);
  }

  public int capacity() {
    return DASHJBLSJNI.PrivateKeyVector_capacity(swigCPtr, this);
  }

  public void reserve(int n) {
    DASHJBLSJNI.PrivateKeyVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return DASHJBLSJNI.PrivateKeyVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    DASHJBLSJNI.PrivateKeyVector_clear(swigCPtr, this);
  }

  public PrivateKeyVector(int count, PrivateKey value) {
    this(DASHJBLSJNI.new_PrivateKeyVector__SWIG_2(count, PrivateKey.getCPtr(value), value), true);
  }

  private int doSize() {
    return DASHJBLSJNI.PrivateKeyVector_doSize(swigCPtr, this);
  }

  private void doAdd(PrivateKey x) {
    DASHJBLSJNI.PrivateKeyVector_doAdd__SWIG_0(swigCPtr, this, PrivateKey.getCPtr(x), x);
  }

  private void doAdd(int index, PrivateKey x) {
    DASHJBLSJNI.PrivateKeyVector_doAdd__SWIG_1(swigCPtr, this, index, PrivateKey.getCPtr(x), x);
  }

  private PrivateKey doRemove(int index) {
    return new PrivateKey(DASHJBLSJNI.PrivateKeyVector_doRemove(swigCPtr, this, index), true);
  }

  private PrivateKey doGet(int index) {
    return new PrivateKey(DASHJBLSJNI.PrivateKeyVector_doGet(swigCPtr, this, index), false);
  }

  private PrivateKey doSet(int index, PrivateKey val) {
    return new PrivateKey(DASHJBLSJNI.PrivateKeyVector_doSet(swigCPtr, this, index, PrivateKey.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    DASHJBLSJNI.PrivateKeyVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
