/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dashj.bls;

public class Uint8Vector extends java.util.AbstractList<Short> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Uint8Vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Uint8Vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DASHJBLSJNI.delete_Uint8Vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Uint8Vector(short[] initialElements) {
    this();
    reserve(initialElements.length);

    for (short element : initialElements) {
      add(element);
    }
  }

  public Uint8Vector(Iterable<Short> initialElements) {
    this();
    for (short element : initialElements) {
      add(element);
    }
  }

  public Short get(int index) {
    return doGet(index);
  }

  public Short set(int index, Short e) {
    return doSet(index, e);
  }

  public boolean add(Short e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Short e) {
    modCount++;
    doAdd(index, e);
  }

  public Short remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public Uint8Vector() {
    this(DASHJBLSJNI.new_Uint8Vector__SWIG_0(), true);
  }

  public Uint8Vector(Uint8Vector other) {
    this(DASHJBLSJNI.new_Uint8Vector__SWIG_1(Uint8Vector.getCPtr(other), other), true);
  }

  public int capacity() {
    return DASHJBLSJNI.Uint8Vector_capacity(swigCPtr, this);
  }

  public void reserve(int n) {
    DASHJBLSJNI.Uint8Vector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return DASHJBLSJNI.Uint8Vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    DASHJBLSJNI.Uint8Vector_clear(swigCPtr, this);
  }

  public Uint8Vector(int count, short value) {
    this(DASHJBLSJNI.new_Uint8Vector__SWIG_2(count, value), true);
  }

  private int doSize() {
    return DASHJBLSJNI.Uint8Vector_doSize(swigCPtr, this);
  }

  private void doAdd(short x) {
    DASHJBLSJNI.Uint8Vector_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, short x) {
    DASHJBLSJNI.Uint8Vector_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private short doRemove(int index) {
    return DASHJBLSJNI.Uint8Vector_doRemove(swigCPtr, this, index);
  }

  private short doGet(int index) {
    return DASHJBLSJNI.Uint8Vector_doGet(swigCPtr, this, index);
  }

  private short doSet(int index, short val) {
    return DASHJBLSJNI.Uint8Vector_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    DASHJBLSJNI.Uint8Vector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
